### PR TITLE
Variant of replies that incorporates errors and decouples emitting events and replying

### PR DESCRIPTION
**Pull request by jrudolph**
Variant of #184

### CODE REVIEW

**Comment by jrudolph** [comment]
Replying is now mandatory as discussed in #184.

**Comment by jrudolph** [comment]
> We could rename everything from reply to result, if possible, thereby potentially creating aliases or proper types (like `CmdResult`).

Would the idea be that the declaration could be:

```rust
#[derive(Debug, Clone, Copy)]
pub enum Cmd {
    Inc(u64, Result<u64, Error>),
    Dec(u64, Result<u64, Error>),
}
```

where `Result` (or `CmdResult`) would be a new type that represents what is currently `Reply<std::result::Result<T, E>>`?

I think I wouldn't call it `Result` to avoid confusion with the actual result type. After all, this declaration is still only a marker type.

**Comment by jrudolph** [comment]
> where `Result` (or `CmdResult`) would be a new type that represents what is currently `Reply<std::result::Result<T, E>>`?

Did that in the latest commit.

**Comment by hseeberger** [comment]
Very nice. I still have to take a deeper look, but I think we are getting there.

Yeah, naming is not satisfying, in particular wrt CmdResult and CommandResult.

**Comment by hseeberger** [comment]
> Should we rename CommandResult to CommandAction?

There should not be `Command` at all, only `Cmd`. Hence `CmdAction`. Or `CmdEffect`. Or ...

**Comment by hseeberger** [comment]
Could we get rid of `CmdResult`, at least in the user facing API? Maybe use macro magic? Or didn't you mention somewhere earlier, that it would not be needed?

**Comment by jrudolph** [comment]
> Could we get rid of `CmdResult`, at least in the user facing API? Maybe use macro magic? Or didn't you mention somewhere earlier, that it would not be needed?

It's currently the only way to specify the result type for a command and it also adds some type-safety because it is impossible (or at least very difficult) to create a reply with the wrong type. So, it currently is necessary for type-safety or otherwise you would have to manually pass the result types to `EntityRef::handle_cmd`.

**Comment by jrudolph** [comment]
> This question includes asynchrony introduced by ES/CQRS and our attempts to „fix“ EventSourced to allow for queries/replies from commands.

Comparing with other ES systems, is it common behavior that you cannot get any consistent answers from a domain object?

**Comment by hseeberger** [comment]
> consistent answer 

What should that be? Could you give an example, please?

**Comment by jrudolph** [comment]
update an entity -> get the latest state after the update

**Comment by hseeberger** [comment]
I see. But isn‘t the latest state potentially outdated when it arrives at the receiver? Is there more consistency than going through a read side?

I am not generally opposed to adding such a feature, I just try to fully understand its value.

**Comment by jrudolph** [comment]
> I see. But isn‘t the latest state potentially outdated when it arrives at the receiver? Is there more consistency than going through a read side?

True, though, for practical purposes, "concurrency" might be less of an issue than a single user being "time-warped" around because reads after writes are only eventually consistent.

Maybe we need to have at least a general discussion (also wrt the UI) about how we want to deal with eventual consistency on a grander scheme.

**Pull request closed without merging**
